apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: external-apps
  namespace: cozy-public
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 60s
  url: https://github.com/klinch0/cozy-exrta-apps.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: main
  namespace: cozy-public
spec:
  force: false
  interval: 10m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-apps
